[package]
name = "rs-chdiff"
version = "0.1.0"

description='''
Create, verify and compare hash sums on whole directory trees.
'''

edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
