name: create rs-chdiff build tools

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'docker-rs/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: docker-rs

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set environment variables
        run: |
          printf "USER_ID=%s\nGROUP_ID=%s\n" "$(id -u)" "$(id -g)"
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: docker-rs
          build-args:
            - USER_ID=${{ env.USER_ID }}
            - GROUP_ID=${{ env.GROUP_ID }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
