name: rs-chdiff-build

on:
  push

jobs:
  build-and-release:
    name: build and release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3

      - name: update toolchain
        run: rustup target list --installed

      - name: update toolchain
        run: rustup update

      - name: update toolchain
        run: rustup target list --installed

      - name: build
        run: ./build.sh
