name: rs-chdiff build dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'docker-rs/**'
      - '.github/workflows/docker-rs.yml'

jobs:
  build-and-release:
    name: build and release
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "docker pull"
        run: |
          printf "%s\n" "${{ secrets.GITHUB_TOKEN }}" \
          | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker pull ghcr.io/soerenkoehler/docker-rs:latest

      - name: "test"
        run: ./build/test.sh

      - name: "compile"
        run: ./build/compile.sh

      - name: "package"
        run: ./build/package.sh

      - name: "create release"
        run: ./build/release.sh
        env:
          GH_TOKEN: ${{ github.token }}
