name: rs-chdiff build main

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docker-rs/**'
      - '.github/workflows/docker-rs.yml'

jobs:
  build-and-release:
    name: build and release
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "login to ghcr.io"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "docker pull"
        run: |
          docker pull ghcr.io/soerenkoehler/docker-rs:${{ github.ref_name }}
          docker tag ghcr.io/soerenkoehler/docker-rs:${{ github.ref_name }} docker-rs:latest

      - name: "test"
        run: ./build/test.sh

      - name: debug
        run: |
          ls -al coverage
          ls -al coverage/html

      - name: SonarQube Scan
        if: ${{ github.ref_name == 'main' }}
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: "compile"
        run: ./build/compile.sh

      - name: "package"
        run: ./build/package.sh

      - name: "create release"
        run: ./build/release.sh
        env:
          GH_TOKEN: ${{ github.token }}
